/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Source: docs/telegram-api-schema.snapshot.json
 */

export type UnknownPayload = Record<string, unknown>;

export type StrictTelegramApiMethodPayloads = {
  answerCallbackQuery: { callback_query_id: string; text?: string } & UnknownPayload;
  answerInlineQuery: { inline_query_id: string; results: unknown[] } & UnknownPayload;
  createInvoiceLink: { title: string; description: string; payload: string; currency: string; prices: unknown[] } & UnknownPayload;
  deleteMessage: { chat_id: number | string; message_id: number } & UnknownPayload;
  deleteWebhook: { drop_pending_updates?: boolean } & UnknownPayload;
  editMessageText: { text: string; chat_id?: number | string; message_id?: number; inline_message_id?: string } & UnknownPayload;
  getStickerSet: { name: string } & UnknownPayload;
  getUpdates: { offset?: number; limit?: number; timeout?: number; allowed_updates?: string[] } & UnknownPayload;
  getWebhookInfo: UnknownPayload;
  sendDocument: { chat_id: number | string; document: string } & UnknownPayload;
  sendInvoice: { chat_id: number | string; title: string; description: string; payload: string; currency: string; prices: unknown[] } & UnknownPayload;
  sendMediaGroup: { chat_id: number | string; media: unknown[] } & UnknownPayload;
  sendMessage: { chat_id: number | string; text: string } & UnknownPayload;
  sendPhoto: { chat_id: number | string; photo: string } & UnknownPayload;
  sendPoll: { chat_id: number | string; question: string; options: string[] } & UnknownPayload;
  sendSticker: { chat_id: number | string; sticker: string } & UnknownPayload;
  setGameScore: { user_id: number; score: number; chat_id?: number | string; message_id?: number; inline_message_id?: string } & UnknownPayload;
  setMessageReaction: { chat_id: number | string; message_id: number; reaction?: unknown[]; is_big?: boolean } & UnknownPayload;
  setWebhook: { url: string; max_connections?: number; allowed_updates?: string[]; drop_pending_updates?: boolean; secret_token?: string } & UnknownPayload;
  uploadStickerFile: { user_id: number; sticker: string; sticker_format: 'static' | 'animated' | 'video' } & UnknownPayload;
};

export type StrictTelegramApiMethodName = keyof StrictTelegramApiMethodPayloads;

export type TelegramApiMethodPayloads = {
  answerCallbackQuery: StrictTelegramApiMethodPayloads['answerCallbackQuery'];
  answerGuestQuery: UnknownPayload;
  answerInlineQuery: StrictTelegramApiMethodPayloads['answerInlineQuery'];
  answerPreCheckoutQuery: UnknownPayload;
  answerShippingQuery: UnknownPayload;
  answerWebAppQuery: UnknownPayload;
  approveChatJoinRequest: UnknownPayload;
  approveSuggestedPost: UnknownPayload;
  banChatMember: UnknownPayload;
  banChatSenderChat: UnknownPayload;
  close: UnknownPayload;
  closeForumTopic: UnknownPayload;
  closeGeneralForumTopic: UnknownPayload;
  convertGiftToStars: UnknownPayload;
  copyMessage: UnknownPayload;
  copyMessages: UnknownPayload;
  createChatInviteLink: UnknownPayload;
  createChatSubscriptionInviteLink: UnknownPayload;
  createForumTopic: UnknownPayload;
  createInvoiceLink: StrictTelegramApiMethodPayloads['createInvoiceLink'];
  createNewStickerSet: UnknownPayload;
  declineChatJoinRequest: UnknownPayload;
  declineSuggestedPost: UnknownPayload;
  deleteAllMessageReactions: UnknownPayload;
  deleteBusinessMessages: UnknownPayload;
  deleteChatPhoto: UnknownPayload;
  deleteChatStickerSet: UnknownPayload;
  deleteForumTopic: UnknownPayload;
  deleteMessage: StrictTelegramApiMethodPayloads['deleteMessage'];
  deleteMessageReaction: UnknownPayload;
  deleteMessages: UnknownPayload;
  deleteMyCommands: UnknownPayload;
  deleteStickerFromSet: UnknownPayload;
  deleteStickerSet: UnknownPayload;
  deleteStory: UnknownPayload;
  deleteWebhook: StrictTelegramApiMethodPayloads['deleteWebhook'];
  editChatInviteLink: UnknownPayload;
  editChatSubscriptionInviteLink: UnknownPayload;
  editForumTopic: UnknownPayload;
  editGeneralForumTopic: UnknownPayload;
  editMessageCaption: UnknownPayload;
  editMessageChecklist: UnknownPayload;
  editMessageLiveLocation: UnknownPayload;
  editMessageMedia: UnknownPayload;
  editMessageReplyMarkup: UnknownPayload;
  editMessageText: StrictTelegramApiMethodPayloads['editMessageText'];
  editStory: UnknownPayload;
  editUserStarSubscription: UnknownPayload;
  exportChatInviteLink: UnknownPayload;
  forwardMessage: UnknownPayload;
  forwardMessages: UnknownPayload;
  getAvailableGifts: UnknownPayload;
  getBusinessAccountGifts: UnknownPayload;
  getBusinessAccountStarBalance: UnknownPayload;
  getBusinessConnection: UnknownPayload;
  getChat: UnknownPayload;
  getChatAdministrators: UnknownPayload;
  getChatGifts: UnknownPayload;
  getChatMember: UnknownPayload;
  getChatMemberCount: UnknownPayload;
  getChatMenuButton: UnknownPayload;
  getCustomEmojiStickers: UnknownPayload;
  getFile: UnknownPayload;
  getForumTopicIconStickers: UnknownPayload;
  getGameHighScores: UnknownPayload;
  getManagedBotAccessSettings: UnknownPayload;
  getManagedBotToken: UnknownPayload;
  getMe: UnknownPayload;
  getMyCommands: UnknownPayload;
  getMyDefaultAdministratorRights: UnknownPayload;
  getMyDescription: UnknownPayload;
  getMyName: UnknownPayload;
  getMyShortDescription: UnknownPayload;
  getMyStarBalance: UnknownPayload;
  getStarTransactions: UnknownPayload;
  getStickerSet: StrictTelegramApiMethodPayloads['getStickerSet'];
  getUpdates: StrictTelegramApiMethodPayloads['getUpdates'];
  getUserChatBoosts: UnknownPayload;
  getUserGifts: UnknownPayload;
  getUserPersonalChatMessages: UnknownPayload;
  getUserProfileAudios: UnknownPayload;
  getUserProfilePhotos: UnknownPayload;
  getWebhookInfo: StrictTelegramApiMethodPayloads['getWebhookInfo'];
  giftPremiumSubscription: UnknownPayload;
  hideGeneralForumTopic: UnknownPayload;
  leaveChat: UnknownPayload;
  logOut: UnknownPayload;
  pinChatMessage: UnknownPayload;
  postStory: UnknownPayload;
  promoteChatMember: UnknownPayload;
  readBusinessMessage: UnknownPayload;
  refundStarPayment: UnknownPayload;
  removeBusinessAccountProfilePhoto: UnknownPayload;
  removeChatVerification: UnknownPayload;
  removeMyProfilePhoto: UnknownPayload;
  removeUserVerification: UnknownPayload;
  reopenForumTopic: UnknownPayload;
  reopenGeneralForumTopic: UnknownPayload;
  replaceManagedBotToken: UnknownPayload;
  replaceStickerInSet: UnknownPayload;
  restrictChatMember: UnknownPayload;
  revokeChatInviteLink: UnknownPayload;
  savePreparedInlineMessage: UnknownPayload;
  savePreparedKeyboardButton: UnknownPayload;
  sendAnimation: UnknownPayload;
  sendAudio: UnknownPayload;
  sendChatAction: UnknownPayload;
  sendChecklist: UnknownPayload;
  sendContact: UnknownPayload;
  sendDice: UnknownPayload;
  sendDocument: StrictTelegramApiMethodPayloads['sendDocument'];
  sendGame: UnknownPayload;
  sendGift: UnknownPayload;
  sendInvoice: StrictTelegramApiMethodPayloads['sendInvoice'];
  sendLivePhoto: UnknownPayload;
  sendLocation: UnknownPayload;
  sendMediaGroup: StrictTelegramApiMethodPayloads['sendMediaGroup'];
  sendMessage: StrictTelegramApiMethodPayloads['sendMessage'];
  sendMessageDraft: UnknownPayload;
  sendPaidMedia: UnknownPayload;
  sendPhoto: StrictTelegramApiMethodPayloads['sendPhoto'];
  sendPoll: StrictTelegramApiMethodPayloads['sendPoll'];
  sendSticker: StrictTelegramApiMethodPayloads['sendSticker'];
  sendVenue: UnknownPayload;
  sendVideo: UnknownPayload;
  sendVideoNote: UnknownPayload;
  sendVoice: UnknownPayload;
  setBusinessAccountBio: UnknownPayload;
  setBusinessAccountGiftSettings: UnknownPayload;
  setBusinessAccountName: UnknownPayload;
  setBusinessAccountProfilePhoto: UnknownPayload;
  setBusinessAccountUsername: UnknownPayload;
  setChatAdministratorCustomTitle: UnknownPayload;
  setChatDescription: UnknownPayload;
  setChatMemberTag: UnknownPayload;
  setChatMenuButton: UnknownPayload;
  setChatPermissions: UnknownPayload;
  setChatPhoto: UnknownPayload;
  setChatStickerSet: UnknownPayload;
  setChatTitle: UnknownPayload;
  setCustomEmojiStickerSetThumbnail: UnknownPayload;
  setGameScore: StrictTelegramApiMethodPayloads['setGameScore'];
  setManagedBotAccessSettings: UnknownPayload;
  setMessageReaction: StrictTelegramApiMethodPayloads['setMessageReaction'];
  setMyCommands: UnknownPayload;
  setMyDefaultAdministratorRights: UnknownPayload;
  setMyDescription: UnknownPayload;
  setMyName: UnknownPayload;
  setMyProfilePhoto: UnknownPayload;
  setMyShortDescription: UnknownPayload;
  setPassportDataErrors: UnknownPayload;
  setStickerEmojiList: UnknownPayload;
  setStickerKeywords: UnknownPayload;
  setStickerMaskPosition: UnknownPayload;
  setStickerPositionInSet: UnknownPayload;
  setStickerSetThumbnail: UnknownPayload;
  setStickerSetTitle: UnknownPayload;
  setUserEmojiStatus: UnknownPayload;
  setWebhook: StrictTelegramApiMethodPayloads['setWebhook'];
  stopMessageLiveLocation: UnknownPayload;
  stopPoll: UnknownPayload;
  transferBusinessAccountStars: UnknownPayload;
  transferGift: UnknownPayload;
  unbanChatMember: UnknownPayload;
  unbanChatSenderChat: UnknownPayload;
  unhideGeneralForumTopic: UnknownPayload;
  unpinAllChatMessages: UnknownPayload;
  unpinAllForumTopicMessages: UnknownPayload;
  unpinAllGeneralForumTopicMessages: UnknownPayload;
  unpinChatMessage: UnknownPayload;
  uploadStickerFile: StrictTelegramApiMethodPayloads['uploadStickerFile'];
  verifyChat: UnknownPayload;
  verifyUser: UnknownPayload;
};
